### ISSUE TITLE
Seeing errors with a couple of reports in Sitecore 9.2

### ISSUE THREAD

**Issue by Jen-Pearson** [Sitecore/AdvancedSystemReporter#10]
Colleague is seeing this when running Aliases and Locked Items reports.  Active Aliases report loads fine however.  Any pointers on where to look for an issue perhaps in installation in his environment.  

From log:
5428 14:13:08 WARN  ASR: cannot assign value to property  in type ASR.Reports.Viewers.AliasViewer
5428 14:13:08 WARN  ASR: cannot assign value to property  in type ASR.Reports.Items.ItemViewer
5428 14:13:08 WARN  ASR: cannot assign value to property  in type ASR.Reports.Items.ItemViewer
5428 14:13:08 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Web.UI.Sheer.BaseForm.HandleMessage(Message message)
   at ASR.App.MainForm.HandleMessage(Message message)
   at Sitecore.Shell.Framework.Commands.MessageCommand.Execute(CommandContext context)
   at Sitecore.Web.UI.Sheer.ClientPage.Dispatch(String command)
   at Sitecore.Web.UI.Sheer.ClientPage.RaiseEvent()
   at Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: ASR.Reports
   at ASR.Reports.Viewers.AliasViewer.InitializeAlias(Database db)
   at ASR.Reports.Viewers.AliasViewer.GetAlias(Item item)
   at ASR.Reports.Viewers.AliasViewer.Display(DisplayElement dElement)
   at ASR.Interface.Report.IntializeDisplayElement(Object resultItem)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ASR.Interface.Report.DisplayElements(Int32 start, Int32 count)
   at ASR.App.MainForm.PopulateItemList(Int32 start, Int32 count)
   at ASR.App.MainForm.RunFinished(Message message)

**Comment by Jen-Pearson** [comment]
In Master - the viewer items are erroring:
![viewer-error](https://user-images.githubusercontent.com/8033039/77886169-17f78a80-72b4-11ea-8dba-9d7a10fc1687.png)

**Comment by Jen-Pearson** [comment]
Ok the problem file is Column.XMl calling that getString.  Now to figure out why my colleague's Aliases and Broken Links reports don't load properly.  Not sure if its related to the AllItems scanner or the fact he's using multisite.
